### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-zhrksoew#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by vikrant0017** [comment]
This issue has been resolved in #3 .
![fix-screenshot-1](https://user-images.githubusercontent.com/96116296/200246910-feb239a9-983e-48cd-91ee-bf1fd65a7b1f.png)
![fix-screenshot-2](https://user-images.githubusercontent.com/96116296/200246918-853ca130-1d54-44ba-8825-ce33f027af6c.png)
![fix-screenshot-3](https://user-images.githubusercontent.com/96116296/200246921-94d715f3-b1e9-4340-9223-c91d0511b3fc.png)
